[package]
name = "fetch-moots"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
futures = "0.3.30"
reqwest = "0.12.8"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
